name: Sanity Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Sanity Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Do sanity checks
        run: make sanity

      - name: Run golangci-lint
        run: make lint

      - name: Run unit tests
        run: make test
